server:
  port: 8083

spring:
  webflux:
    base-path: "/rate"
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      host: luz-del-alba.eastus.cloudapp.azure.com
      database: admin
      username: root
      password: password
      port: 27017