server:
  port: 8083
  servlet:
    context-path: "/rate"

spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      host: mongo
      database: rate
      username: root
      password: password
      port: 27017